### ISSUE TITLE
baseline mass profile is unnecessarily complex

### ISSUE THREAD

**Issue by MartinBrown2000** [MartinBrown2000/waste-impact-calculator#8]
Currently when the baseline mass profile is created, it includes "production" tons and "end of life transport" tons.  This is formally correct, in the sense that this is the mass information needed to multiply by impact factors to get impacts.  But

* in practicality it is awkward because much of the tons tracking is really only about "end of life" and not production or transport.  I find myself writing extra lines of code to filter out those tons.
* in practicality it is unnecessary, since the left_join() with the impact factor file ends up creating production and end-of-life transport tons anyway.

__Ergo: The import syntax files (for both the deq and the warm versions of the ARR analysis) should be simplified so they only yield "end-of-life" tons.__

**Comment by Stomper2008** [comment]
i worked on this some with the "import waste data" and "create ARR results with DEQ factors" markdown files.  it's not fully expressed yet. 

changes here may affect the app.

**Comment by Stomper2008** [comment]
I believe this can be closed.  What's happened is that the "observed waste" file should contain ONLY what has been imported from the databases.  Observed waste is then evaluated against a particular set of impact factors to create a matched set of impact factors and baseline mass profile.  So far this scheme has only been executed for ARR SCENARIOS WITH DEQ FACTORS project, but it could be executed for others.
